---
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: my-sonarqube
    meta.helm.sh/release-namespace: default
  creationTimestamp: '2024-02-20T14:26:30Z'
  labels:
    app: sonarqube
    app.kubernetes.io/managed-by: Helm
    chart: sonarqube-10.4.0_2288
    heritage: Helm
    release: my-sonarqube
  name: my-sonarqube-sonarqube
  namespace: default
  resourceVersion: '330813'
  uid: b0352b2a-4ca2-45da-be59-4a6539782591
spec:
  clusterIP: 10.104.35.131
  clusterIPs: [10.104.35.131]
  internalTrafficPolicy: Cluster
  ipFamilies: [IPv4]
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 9000
      protocol: TCP
    # targetPort: http
      targetPort: 8088
  selector:
    app: sonarqube
    release: my-sonarqube
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
