---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chromadb-persistent-volume-claim-nfs
  namespace: databases
  labels:
    storageclass.storage.k8s.io: storage-nfs
    persistentvolumes.k8s.io: chromadb-persistent-volume-nfs
    persistentvolumeclaims.k8s.io: chromadb-persistent-volume-claim-nfs
spec:
  storageClassName: storage-nfs
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 10Gi
