---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: '1'
    deployment.kubernetes.io/max-replicas: '2'
    deployment.kubernetes.io/revision: '1'
    meta.helm.sh/release-name: pod-nginx
    meta.helm.sh/release-namespace: default
  creationTimestamp: '2024-01-30T17:57:37Z'
  generation: 1
  labels:
    app.kubernetes.io/instance: pod-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: 1.25.3
    helm.sh/chart: nginx-15.10.1
    # pod-template-hash: 5c45bc87
  name: pod-nginx
  namespace: default
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: pod-nginx
  #   uid: 57024ab1-2e21-42ae-bd5e-2a17ab8ca10b
# resourceVersion: "19802"
# uid: 15e5cd88-a180-41fa-bde2-18648be58c30
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: pod-nginx
      app.kubernetes.io/name: nginx
      # pod-template-hash: 5c45bc87
  template:
    metadata:
      creationTimestamp:
      labels:
        app.kubernetes.io/instance: pod-nginx
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: nginx
        app.kubernetes.io/version: 1.25.3
        helm.sh/chart: nginx-15.10.1
        # pod-template-hash: 5c45bc87
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: pod-nginx
                    app.kubernetes.io/name: nginx
                topologyKey: kubernetes.io/hostname
              weight: 1
      automountServiceAccountToken: false
      containers:
        - env:
            - name: BITNAMI_DEBUG
              value: 'false'
            - name: NGINX_HTTP_PORT_NUMBER
              value: '8080'
          image: docker.io/bitnami/nginx:1.25.3-debian-11-r6
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 5
          name: nginx
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 3
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
      serviceAccount: pod-nginx
      serviceAccountName: pod-nginx
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
# status:
#   availableReplicas: 1
#   fullyLabeledReplicas: 1
#   observedGeneration: 1
#   readyReplicas: 1
#   replicas: 1
