# Source: https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-port-nodeport
  namespace: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
      nodePort: 30003
  selector:
    app: postgres
