---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: postgres
          image: postgres:12.17
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
          resources:
            limits:
              cpu: 200m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 32Mi
      volumes:
        - name: postgresdata
        # persistentVolumeClaim:
        #   claimName: postgres-volume-claim
          hostPath:
            path: /home/tzahi/postgres  # directory location on host
            type: DirectoryOrCreate  # this field is optional
