---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-persistent-volume-nfs-claim
  namespace: databases
  labels:
    app: postgres-persistent-volume-nfs-claim
spec:
  storageClassName: storage-nfs
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 10Gi
