---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-persistent-volume-claim-nfs
  namespace: postgres
  labels:
    app: postgres-persistent-volume-claim-nfs
spec:
  storageClassName: storage-nfs
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 2Gi
