---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  containers:
    - image: busybox
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
      name: busybox
      resources:
        requests:
          memory: "32Mi"
          cpu: "50m"
        limits:
          memory: "64Mi"
          cpu: "100m"
  restartPolicy: Always


# spec:
#   containers:
#   - name: app
#     image: images.my-company.example/app:v4
#     resources:
#       requests:
#         memory: "64Mi"
#         cpu: "250m"
#       limits:
#         memory: "128Mi"
#         cpu: "500m"
