---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-persistentvolume-nfs
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: awx-persistentvolume-nfs
  mountOptions: [hard, nfsvers=4.1]
  nfs:
    path: /mnt/sharedfolder/awx
    server: 192.168.50.79
    readOnly: false
