---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-nfs
provisioner: storage.io/storage-nfs
reclaimPolicy: Retain
# reclaimPolicy: Delete
# volumeBindingMode: Immediate
allowVolumeExpansion: true
# mountOptions:
#   - debug
parameters:
  # server: 192.168.50.50
  server: 172.22.54.208
  path: /home/tzahi/storage
  readOnly: 'false'

## setup nfs server in wsl2
# /home/tzahi/nfsshare *(rw,fsid=0,async,no_subtree_check,no_auth_nlm,insecure,no_root_squash)
