---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: splunk-persistent-volume-nfs
  labels:
    app: storage-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage-nfs
  nfs:
    path: /home/tzahi/storage/splunk
    server: 172.22.54.208
    readOnly: false
