---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-persistent-volume-nfs-claim
  labels:
    app: splunk-persistent-volume-nfs-claim
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: splunk
    meta.helm.sh/release-namespace: default
  annotations:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: splunk
    meta.helm.sh/release-namespace: default
spec:
  storageClassName: storage-nfs
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 10Gi
