---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-persistent-volume-nfs
  labels:
    app: storage-nfs
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage-nfs
  nfs:
    path: /home/tzahi/storage/mongodb
    server: 172.22.54.171
    readOnly: false
