# Source: eck-operator/templates/service-account.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-operator
  namespace: elastic
  labels:
    control-plane: elastic-operator
    app.kubernetes.io/version: "1.5.0"
