# Source: eck-operator/templates/webhook.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-webhook-server-cert
  namespace: elastic
  labels:
    control-plane: elastic-operator
    app.kubernetes.io/version: "1.5.0"
