---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - elasticsearch-namespace.yml
  - elasticsearch-configmap.yml
  - elasticsearch-service.yml
  - elasticsearch-statefulset.yaml
  - elasticsearch-serviceaccount.yaml
  - elasticsearch-secret.yaml
  - elasticsearch-clusterrole.yaml
  - elasticsearch-clusterrolebinding.yaml
  - elasticsearch-customresourcedefinition.yaml
  - elasticsearch-validatingwebhookconfiguration.yaml
# - elasticsearch-volume-persistent-nfs.yml
# - elasticsearch-volume-persistent-claim.yml

# - jenkins-statefulset.yml
# run this on first time  ../sharedResources/general-storageclass-nfs.yml
# kubectl kustomize <kustomization_directory>
# kubectl apply -k <kustomization_directory>
