---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - targetPort: 80  # the pod internal port
      port: 80  # the kubernetes service port
      nodePort: 30009  # the node port, external kubernetes access
  selector:
    app: myapp
    type: front-end
