---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-persistent-volume-nfs
  labels:
    app: storage-nfs
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage-nfs
  nfs:
    path: /home/tzahi/nfsshare/storage/nginx
    server: 172.22.54.208
    readOnly: false
