---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-port
  namespace: nginx
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 80
      # nodePort: 30022
  selector:
    app: nginx
