---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-persistent-volume-claim
  labels:
    storageclass.storage.k8s.io: jenkins-persistent-volume-claim
  namespace: jenkins
spec:
  storageClassName: storage-nfs
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 5Gi
