---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-persistent-volume-claim-nfs
  namespace: jenkins
  labels:
    app: jenkins-persistent-volume-claim-nfs
spec:
  storageClassName: storage-nfs
  accessModes: [ReadWriteMany]
  resources:
    requests:
    storage: 5Gi
