---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
  namespace: jenkins
spec:
  serviceName: jenkins
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:2.450-alpine-jdk21
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: jenkins-home-mount
              mountPath: /var/jenkins_home
            - name: jenkins-file-mount
              mountPath: /tmp/jenkins-file
              subPath: jenkins-file
          env:
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: jenkins-environment-variables
                  key: JAVA_OPTS
      volumes:
        - name: jenkins-home-mount
          persistentVolumeClaim:
            claimName: jenkins-persistent-volume-claim-nfs
        - name: jenkins-file-mount
          configMap:
            name: jenkins-file
            optional: false
            items:
              - key: TESTING
                path: "jenkins-file"
      restartPolicy: Always
      # volumeMounts:
      # - name: myvol
      #   subPath: mykey
      #   mountPath: /etc/shadow

# items:
#   - key: TESTING
#     path: TESTING
# hostPath:
# path: /tmp/jenkinsVolume  # directory location on host
# type: DirectoryOrCreate  # this field is optional
# volumeClaimTemplates:
# - metadata:
#     name: jenkins-home-mount
#   spec:
#     accessModes:
#     - ReadWriteMany
#     storageClassName: storage-nfs
#     resources:
#       requests:
#         storage: 10Gi
