---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage-persistent-volume
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/c/repository/KubernetesExamples/jenkins/jenkins_home
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [docker-desktop]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-storage-persistent-volume-claim
  namespace: jenkins
  labels:
    app: jenkins
spec:
  storageClassName: local-storage
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
