---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-persistent-volume
  labels:
    app.kubernetes.io/namespase: database
    storageclass.storage.k8s.io: storage-nfs
    persistentvolumes.k8s.io: jenkins-persistent-volume-nfs
    persistentvolumeclaims.k8s.io: jenkins-persistent-volume-claim-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage-nfs
  # mountOptions:
  #   - nfsvers=4.1
  nfs:
    path: /home/tzahi/storage/jenkins
    server: 172.22.54.208
    readOnly: false
