apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jenkins-namespace.yml
  - jenkins-configmap.yml
  - jenkins-service.yml
  - jenkins-persistent-volume-nfs.yml
  - jenkins-persistent-volume-claim.yml
# - jenkins-statefulset.yml

# run this on first time  ../sharedResources/general-storageclass-nfs.yml
# kubectl kustomize <kustomization_directory>
# kubectl apply -k <kustomization_directory>
