---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jenkins-namespace.yml
  - jenkins-configmap.yml
  - jenkins-service.yml
  - ../sharedResources/general-storageclass-nfs.yml
  - jenkins-volume-persistent-nfs.yml
  - jenkins-volume-persistent-claim.yml
# - jenkins-statefulset.yml

# kubectl kustomize <kustomization_directory>
# kubectl apply -k <kustomization_directory>
