---
apiVersion: v1
kind: Service
metadata:
  name: artifactory-service-port
  namespace: artifactory
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: artifactory
