---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jira
  name: jira
  namespace: jira
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: jira
  type: LoadBalancer
