---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-persistent-volume-nfs
  labels:
    app: storage-nfs
  namespace: jira
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage-nfs
  nfs:
    path: /home/tzahi/nfsshare/storage/jira_home
    server: 172.22.54.208
    readOnly: false
