---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-nfs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions: [hard, nfsvers=4.1]
  nfs:
    path: /mnt/sharedfolder
    server: 192.168.50.79
    readOnly: false
