---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    app: nginx-replicaset
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: nginx-container-replicaset
          image: nginx
          volumeMounts:
            - mountPath: /home/tzahi/ShareStorage/nginx
              name: nginx-volume
      volumes:
        - name: nginx-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
spec:
  selector:
    tier: frontend
  # ports:
  type: LoadBalancer
    # - protocol: TCP
    #   port: 80
    #   targetPort: 9376
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  ports:
    - port: 9376
      targetPort: 80
      nodePort: 30022
