---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lancedb-deployment
  namespace: databases
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: lancedb
          image: lancedb/lancedb:latest
